// Supabase Konfiguration
const SUPABASE_URL = 'https://grbrnkbowqpwmsmalxlc.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyYnJua2Jvd3Fwd21zbWFseGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMjEzOTIsImV4cCI6MjA3ODc5NzM5Mn0.X6FRfX5H3Fd0agUaMJlsUi6uY8YlS1OeZz4uxaW76fw';
